package com.yepher.jsondoc.samples.one;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.yepher.jsondoc.objc.ObjcClassListDriverBase;

public class GenerateObjC extends ObjcClassListDriverBase {

	 private List<Class<?>> pdusToGenerate = new ArrayList<Class<?>>(Arrays.asList(
			 CreateUserRequest.class,
             CreateUserResponse.class
         ));
	 
	 private Set<Class<?>> pdusToExclude = new HashSet<Class<?>>();
	

	@Override
	protected Set<Class<?>> getPdusToExclude() {
		System.out.println("getPdusToExclude()");
		return pdusToExclude;
	}

	@Override
	protected List<Class<?>> getPdusToDocument() {
		System.out.println("getPdusToDocument()");
		return pdusToGenerate;
	}

	@Override
	protected String getTitle() {
		System.out.println("getTitle()");
		return null;
	}

	@Override
	public String getOutputPath() {
		System.out.println("getOutputPath()");
		return "/tmp/yfr_gen";
	}

	@Override
	public void addPduToDocument(Class<?> clazz) {
		System.out.println("addPduToDocument(" + clazz.getName() + "0)");
		
	}

	@Override
	public String getClassPrefix() {
		System.out.println("getClassPrefix()");
		return "YFR";
	}

	@Override
	public String getBanner() {
		System.out.println("getBanner()");
		return "//\n"
			    + "//  !!! WARNING: This code is auto generated by https://github.com/yepher/json-doc !!! \n"
				+ "//\n"
				+ "//  Created " + new Date() + "\n"
				+ "//\n";
	}
	
	public static void main(String[] args) throws Exception {
        new GenerateObjC().run(args);
    }

	@Override
	public boolean isInPackage(String packageName) {
		if (packageName == null) {
			return false;
		}
		return packageName.contains("com.yepher.jsondoc.samples.one");
	}

}
